// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs xlsx-viewer`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "xlsx-to-csv",
    "icon": "📤",
    "name": {
      "en": "XLSX to CSV",
      "ja": "XLSX→CSV分割",
      "zh": "XLSX 转 CSV",
      "de": "XLSX zu CSV",
      "es": "XLSX a CSV"
    },
    "desc": {
      "en": "Split an Excel workbook into one CSV per sheet, zipped.",
      "ja": "Excelブックを1シート1CSVに分割してZIPで出力。",
      "zh": "将 Excel 工作簿按工作表拆分为多个 CSV，打包为 ZIP。",
      "de": "Teilt eine Excel-Arbeitsmappe in je eine CSV pro Blatt auf, als ZIP.",
      "es": "Divide un libro de Excel en un CSV por hoja, comprimido en ZIP."
    }
  },
  {
    "slug": "compare-xlsx",
    "icon": "⚖️",
    "name": {
      "en": "Compare Excel Workbooks",
      "ja": "Excel比較",
      "zh": "比较 Excel 工作簿",
      "de": "Excel-Arbeitsmappen vergleichen",
      "es": "Comparar libros de Excel"
    },
    "desc": {
      "en": "Compare two Excel workbooks cell by cell, sheet by sheet.",
      "ja": "2つのExcelブックをシート・セル単位で比較。",
      "zh": "按工作表和单元格逐一比较两个 Excel 工作簿。",
      "de": "Vergleicht zwei Excel-Arbeitsmappen Blatt für Blatt, Zelle für Zelle.",
      "es": "Compara dos libros de Excel hoja por hoja, celda por celda."
    }
  },
  {
    "slug": "csv-viewer",
    "icon": "📊",
    "name": {
      "en": "CSV Viewer",
      "ja": "CSV ビューア",
      "zh": "CSV 查看器",
      "de": "CSV-Viewer",
      "es": "Visor de CSV"
    },
    "desc": {
      "en": "Open and read CSV files right in your browser.",
      "ja": "CSV ファイルをブラウザで開いて表示します。",
      "zh": "在浏览器里打开并查看 CSV 文件。",
      "de": "CSV-Dateien direkt im Browser öffnen und ansehen.",
      "es": "Abre y consulta archivos CSV en tu navegador."
    }
  },
  {
    "slug": "xls-to-xlsx",
    "icon": "⬆️",
    "name": {
      "en": "XLS to XLSX Converter",
      "ja": "XLS→XLSX変換",
      "zh": "XLS 转 XLSX",
      "de": "XLS-zu-XLSX-Konverter",
      "es": "Convertidor de XLS a XLSX"
    },
    "desc": {
      "en": "Convert a legacy Excel 97-2003 .xls file to modern .xlsx.",
      "ja": "旧形式の.xlsファイルを現行の.xlsxに変換。",
      "zh": "将旧版 Excel 97-2003 的 .xls 文件转换为现代 .xlsx。",
      "de": "Wandelt eine alte Excel-97-2003-.xls-Datei in modernes .xlsx um.",
      "es": "Convierte un archivo .xls antiguo de Excel 97-2003 a .xlsx moderno."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'xlsx-viewer';
